saihan/user/__init__.py
# coding:utf-8

from flask import Blueprint


# 创建蓝图对象
app_user = Blueprint("user", __name__, template_folder="./templates")


# 导入蓝图的视图
from . import views

saihan/user/views.py
# coding:utf-8

from . import app_user
from saihan import db
from flask import render_template, url_for, redirect,request
from saihan.models import Product, Order, Profile, Cart,Address
from flask_login import current_user, login_required
# from saihan.models import ...

# 购物车
# @app_user.route("/cart")
# @login_required
# def user_cart():
    # cart=Cart.query.filter_by(user_id=).all()
    # carts=[]
    # for item in cart:
    #     product=Product.query.filter_by(id=item.product_id)
    #     carts.append({
    #     'attachments':'product.attachments',
    #     'description':'product.description',
    #     'price':'product.price'        
    # })

    # cart={
    #     'attachments':'Product.attachments',
    #     'description':'Product.description',
    #     'price':'Product.price'        
    # }
    # cart = Cart.query.filter_by(user_id=current_user.id)
    # products = []
    # for item in cart:
    #     product = Product.query.filter_by(id=item.product_id).first()
    #     products.append(product)
    # return render_template("user_cart.html",
    #                        user=current_user,
    #                        cart=cart,
    #                        products=products,
    #                        length=len(products))
    
    # print(help(url_for))



# 提交订单界面
@app_user.route("/place_order/")
@app_user.route("/place_order/<int:product_id>")
@login_required
def place_order(product_id=None):
    if product_id == None:
        return redirect(url_for("common.index"))
    product = Product.query.filter_by(id=product_id).first()
    address = Address.query.filter_by(user_id=current_user.id).first()
    return render_template("place_order.html",
                            product=product,
                            address=address)


# 商品详细信息
@app_user.route('/detail/<int:product_id>')
@login_required
def detail(product_id=None):
    product = Product.query.filter_by(id=product_id).first()
    return render_template("product_detail.html", 
                            product=product, 
                            user=current_user)

# @app_user.route('/detail/buy/<int:product_id>')
# @login_required
# def add_to_cart(product_id):
#     product = Product.query.filter_by(id=product_id).first()
#     if product.status == "SELLED":
#         return redirect(url_for("common.error", error="商品已售出"))
#     else:
#         cart = Cart(user_id=current_user.id, product_id=product_id)
#         db.session.add(cart)
#         db.session.commit()
#     return redirect(url_for("user.detail", product_id=product_id))


# @app_user.route('/cart/remove/<int:product_id>')
# @login_required
# def remove_from_cart(product_id):
#     item = Cart.query.filter_by(product_id=product_id, user_id=current_user.id).first()
#     db.session.delete(item)
#     db.session.commit()
#     return redirect(url_for("user.user_cart"))


# 个人简介
@app_user.route('/info')
@login_required
def user_info():
    user = current_user
    profile = Profile.query.filter_by(user_id=user.id).first()
    if not profile:
        profile = Profile(user_id=user.id, mobile="11111111111", nickname=user.username, avatar="saihan.png")
        db.session.add(profile)
        db.session.commit()
    profile_img = url_for("static", filename="images/usericon/"+profile.avatar)
    return render_template("user_info.html", 
                           profile=profile, 
                           profile_img=profile_img,
                           user=current_user)


# 我的订单
@app_user.route('/order')
@login_required
def user_order():

#         Order　　　        订单
# ----------------------------------
# id              订单id
# product_id      商品id
# buyer_id        买家id
# status          状态
# comments       　备注

    orders = Order.query.filter_by(buyer_id=current_user.id).all()
    l = []
    for order in orders:
        product = Product.query.filter_by(id=order.product_id).first()
        l.append(product)
    # orders = current_user.profile[0].orders
    dic = {
        "PENDING":"未付款",
        "PURCHASED":'买家已付款',
        "DELIVERED":'卖家已发货',
        "COMPLETED":'已完成',
        "CANCELLED":"已取消"
    }
    print(len(orders))
    return render_template("user_order.html",
                           orders=orders,
                           user=current_user,
                           l = l,
                           dic = dic,
                           length=len(orders))

# 收货地址
@app_user.route('/site', methods=["GET","POST"])
@login_required
def user_site():

#     Address          　　　　　　　地址
# ----------------------------------
# id          　　　　　　　　　　　　主键
# user_id     　　　　　　　　　　　　用户id
# country     　　　　　　　　　　　　国家
# province    　　　　　　　　　　　　省
# city        　　　　　　　　　　　　城市
# street      　　　　　　　　　　　　街道
# name        　　　　　　　　　　　　联系人姓名
# phone       　　　　　　　　　　　　联系人电话
    addresses = Address.query.filter_by(user_id=current_user.id).all()

    if request.method == "GET":

        return render_template("user_site.html",
                                user=current_user,
                                addresses=addresses,
                                length=len(addresses))

    name = request.form.get('name')
    phone = request.form.get('phone')
    country = request.form.get('country')
    city = request.form.get('city')
    street = request.form.get('street')
    province = request.form.get('province')
    address = Address(user_id=current_user.id,name=name,phone=phone,country=country,city=city,street=street,province=province)
    print(address)
    db.session.add(address)
    db.session.commit()
    addresses = Address.query.filter_by(user_id=current_user.id).all()
    return render_template("user_site.html",
                            user=current_user,
                            addresses=addresses,
                            length=len(addresses))

# 实名认证
@app_user.route('/auth')
@login_required
def user_auth():
    return render_template("user_auth.html",  user=current_user)


@app_user.route('/remove_site/<int:site_id>')
def remove_site(site_id):
    site = Address.query.filter_by(id=site_id).first()
    db.session.delete(site)
    db.session.commit()
    addresses = Address.query.filter_by(user_id=current_user.id).all()
    return redirect(url_for("user.user_site",
                            user=current_user,
                            addresses=addresses,
                            length=len(addresses)))

# 付款页面
@app_user.route('/pay')
@login_required
def user_pay():
    return render_template("pay.html")

saihan/user/templates/pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>确认支付</title>
    <style>
        body{
            text-align: center;
        }
    </style>
</head>
<body>

    <img src="{{ url_for('static', filename='images/payicons/pay.jpg') }}"></img>
    <p>
        <a href="{{ url_for('common.index') }}" type="submit">支付完成，回到首页</a>
    </p>
    
</body>
</html>

saihan/user/templates/user_auth.html
{% extends "userlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:180%;margin: -10px"
		></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{{url_for('user.user_info')}}">· 个人信息</a></li>
				<li><a href="{{url_for('user.user_order')}}">· 全部订单</a></li>
				<li><a href="{{url_for('user.user_site')}}">· 收货地址</a></li>
				<li><a href="{{url_for('user.user_auth')}}" class="active">· 实名认证</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">			
			<h3 class="common_title2">实名认证</h3>
			<div class="has_view_list">
				<div class="reg_form clearfix">
					<form>
						<ul>
							<li>
								<label>证件号:</label>
								<input type="text" name="cpwd" id="cpwd">
								<!-- <span class="error_tip">提示信息</span> -->
							</li>
							<li>
								<label>证件照片:</label>
								<input type="file" name="filename" style="border: none;background-color: white;margin-top: 8px;">
								<!-- <input type="text" name="email" id="email">
								<span class="error_tip">提示信息</span> -->
							</li>
							<li class="reg_sub">
								<input type="submit" value="提 交" name="">
							</li>
						</ul>				
					</form>
				</div>
			</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 天津赛汉科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/user/templates/user_cart.html
{% extends "userlayout.html" %}
{% block body %}
 <body>
	<!-- 1. 导航 -->
		<!-- 2. 横幅banner -->
		<!-- <div id="banner">
			<img src="static/images/images1/banner1.jpg">
		</div> -->
		<!-- 3. 推荐 -->
		<!-- <div id="commend">
			<a href="">
				<img src="static/images/images1/{{photo}}">
			</a>

			<a href="">
				<img src="static/images/images1/{{photo}}">
			</a>
			<a href="">
				<img src="static/images/images1/{{photo}}">
			</a>
			<a href="">
				<img src="static/images/images1/{{photo}}" class="lastImg">
			</a>
		</div> -->
		<!-- 4. 主体 -->
	<div id="container">
		<div id="main">
			<!-- 上方标题栏(工具栏)-->
			<div class="title">
				<p class="check-box">
					<input type="checkbox" name="checkAll" id="checkAll">
					全选
				</p>
				<p class="goods">商品</p>
				<p class="price">单价</p>
				<p class="count">数量</p>
				<p class="sum">小计<p>
				<p class="action">操作</p>
			</div>

			<!-- 下方商品记录-->
			<div class="content">
				{% for i in range(length) %}
				<div class="g-item">	
					<p class="check-box">
						<input type="checkbox" name="check">
						<img src="{{ url_for('static', filename='images/products/'+products[i].attachments[0].filename) }}">
					</p>
					<p class="goods">{{ products[i].name }}</p>
					<p class="price">&yen;{{products[i].price}}</p>
					<p class="count">
						<!-- <a href="javascript:void(0)" class="minus">-</a> -->
						<input value="1">
						<!-- <a href="javascript:void(0)" class="add">+</a> -->
					</p>
					<p class="sum">
						<b>&yen;{{products[i].price}}</b>
					</p>
					<a class="action" href="{{ url_for('user.remove_from_cart', product_id=products[i].id) }}">移除</a>
				</div>
				{%endfor%}
			</div>
		
		</div>
		<!-- 5. 底部 -->
		<div id="cart-toolbar">
			<div class="right-toolbar">
				<p class="submit-count">
					已选择<span></span>件商品
				</p>
				<p class="submit-price">
					共计 : <span></span>
				</p>
				<p class="submit-btn">去结算</p>
			</div>
		
		</div>
	
	</div>
 </body>
{% endblock %}

saihan/user/templates/user_info.html
{% extends "userlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:180%;margin: -10px"
		></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{{url_for('user.user_info')}}" class="active">· 个人信息</a></li>
				<li><a href="{{url_for('user.user_order')}}">· 全部订单</a></li>
				<li><a href="{{url_for('user.user_site')}}">· 收货地址</a></li>
				<li><a href="{{url_for('user.user_auth')}}">· 实名认证</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>头像：</span><img style="width:100px;height:100px" src="{{profile_img}}"></li>	
							<li><span>用户昵称：</span>{{profile.nickname}}</li>
							<li><span>联系方式：</span>{{profile.mobile}}</li>	
							<li><span>个人简介：</span>{{profile.info}}</li>		
						</ul>
				</div>

<!-- 
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="static/images/timg.jpg"></a>
					<h4><a href="detail.html">劳力士</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="static/images/timg (1).jpg"></a>
					<h4><a href="#">保时捷</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="static/images/123/p14.jpg"></a>
					<h4><a href="#">保时捷</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="static/images/123/p15.jpg"></a>
					<h4><a href="#">劳斯莱斯</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="static/images/123/p10.jpg"></a>
					<h4><a href="#">名牌手表</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul> -->


		</div>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2018 天津赛汉科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/user/templates/user_order.html
{% extends "userlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:180%;margin: -10px"
		></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{{url_for('user.user_info')}}">· 个人信息</a></li>
				<li><a href="{{url_for('user.user_order')}}" class="active">· 全部订单</a></li>
				<li><a href="{{url_for('user.user_site')}}">· 收货地址</a></li>
				<li><a href="{{url_for('user.user_auth')}}">· 实名认证</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

				<table class="order_list_table w980">
					<thead>
						<tr style="height:50px;">
							<td>订单创建时间</td>
							<td>订单号</td>
							<td>商品详情</td>
							<td>备注</td>
							<td>金额</td>
							<td>状态</td>
						</tr>
					</thead>
					<tbody>
                        {% for i in range(length) %}
						<tr>
							<td width="15%">{{ orders[i].create_time }}</td>
							<td width="15%">{{ orders[i].id }}</td>
							<td width="25%">
								<ul class="order_goods_list clearfix">					
									<li class="col01" style="height:auto;margin-left:10px;"><img src="{{ url_for('static', filename='images/products/'+l[i].attachments[0].filename) }}""></li>
									
									<li class="col02" style="text-align:left;margin-left:30px;">{{l[i].name}}</li>
								</ul>
							</td>
							{% if orders[i].comments == None %}
							<td width="15%">无</li>
							{% else %}
							<td width="15%">{{orders[i].comments}}</li>
							{% endif %}
							<td width="15%">{{l[i].price}}元</td>
							<td width="15%">{{ dic[orders[i].status] }}</td>
							<!-- <td width="15%"><a href="#" class="oper_btn">查看物流</a></td> -->
						</tr>
                        {%endfor%}
					</tbody>
				</table>
				



				{# <ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872933</li>
					<li class="col02 stress">已完成</li>			
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="images/goods02.jpg"></li>
									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元</em></li>	
									<li class="col03">1</li>
									<li class="col04">11.80元</li>	
								</ul>
							</td>
							<!-- <td width="15%">33.60元</td> -->
							<td width="15%">已完成</td>
							<td width="15%"><a href="#" class="oper_btn">查看详情</a></td>
						</tr>
					</tbody>
				</table>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已发货</li>			
				</ul>
				<table class="order_list_table w980">
				<tbody>
					<tr>
						<td width="55%">
							<ul class="order_goods_list clearfix">					
								<li class="col01"><img src="images/goods02.jpg"></li>
								<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元</em></li>	
								<li class="col03">1</li>
								<li class="col04">11.80元</li>	
							</ul>
							<ul class="order_goods_list clearfix">					
								<li class="col01"><img src="images/goods02.jpg"></li>
								<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元</em></li>	
								<li class="col03">1</li>
								<li class="col04">11.80元</li>	
							</ul>
						</td>
						<!-- <td width="15%">33.60元</td> -->
						<td width="15%">已发货</td>
						<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
					</tr>
				</tbody>
				</table> #}

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>




	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2018 天津赛汉科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/user/templates/user_site.html
{% extends "userlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:180%;margin: -10px;"
		></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{{url_for('user.user_info')}}">· 个人信息</a></li>
				<li><a href="{{url_for('user.user_order')}}">· 全部订单</a></li>
				<li><a href="{{url_for('user.user_site')}}" class="active">· 收货地址</a></li>
				<li><a href="{{url_for('user.user_auth')}}">· 实名认证</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
					</dl>					
				</div>
				<div class="site_con">
					<dl>
						<dt>可选地址：</dt>
					{% for i in range(length) %}
						<dd>{{addresses[i].country}} {{addresses[i].province}} {{addresses[i].city}} {{addresses[i].street}} {{addresses[i].name}} {{addresses[i].phone}}
						<a href="{{ url_for('user.remove_site', site_id=addresses[i].id) }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;删除</a></dd>
					{%endfor%}				
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{{ url_for('user.user_site') }}" method="POST">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="name">
						</div>
						<div class="form_group form_group2" style="height: 40px;">
							<label>国家：</label>
							<input type="text" name='country'></input>
						</div>
						<div class="form_group">
							<label>省:</label>
							<input type="text" name="province">
						</div>
						<div class="form_group">
							<label>城市:</label>
							<input type="text" name="city">
						</div>
						<div class="form_group">
							<label>街道详细信息:</label>
							<input type="text" name="street">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2018 天津赛汉科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/user/templates/userlayout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>赛汉-专注二手商品</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/user.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/cart.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/reset.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-1.12.4.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-ui.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/slide.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/cart.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/register.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/seller_items.js')}}"></script>
    <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon">
</head>
<body>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到赛汉!</div>
            <div class="fr">
                {% if current_user.is_authenticated %}
                    <div class="login_info fl" style="display:block;">
                        欢迎您：<em>{{current_user.username}}</em>
                    </div>
                    <div class="login_btn fl">
                        <span>|</span>
                        <a href="{{url_for('common.logout')}}">登出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{{url_for('common.login')}}">登录</a>
                        <span>|</span>
                        <a href="{{url_for('common.register')}}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{{url_for('user.user_info')}}">用户中心</a>
                    <span>|</span>
                    <a href="{{url_for('user.user_order')}}">我的订单</a>
                    <span>|</span>
                    <a href="{{url_for('common.index')}}">首页</a>
                </div>
            </div>
        </div>      
    </div>
{% block body %}
{% endblock %}
</body>
</html>