saihan/seller/__init__.py
# coding:utf-8

from flask import Blueprint


# 创建蓝图对象
app_seller = Blueprint("seller", __name__, template_folder="./templates")


# 导入蓝图的视图
from . import views

saihan/seller/views.py
# coding:utf-8

from . import app_seller
from saihan import db
from flask import render_template,request, url_for, current_app, jsonify
from saihan.models import Product, Profile,ProductMedia,Order
from flask_login import current_user, login_required
import os
import datetime
# from saihan.models import ...


@app_seller.route("/items")
@login_required
def seller_items():
    profile = Profile.query.filter_by(user_id=current_user.id).first()
    products = Product.query.filter_by(seller_id=current_user.id)
    prod_stat = {
        "SELLING":"出售中",
        "SELLED":"已售出"
    }
    # print(url_for("static", filename="images/products/"+products[0].attachments[0].filename))
    return render_template("seller_items.html",
                            profile=profile,
                            products=products,
                            prod_stat=prod_stat)


@app_seller.route("/order",methods=["GET","POST"])
def seller_order():
    # name = Product.query.filter_by(seller_id=current_user.id).all()
    products = Product.query.filter_by(seller_id=current_user.id).all()
    # print(current_app.config["UPLOAD_FOLDER"])
    order_list = []
    product_list = []
    user_list = []
    for product in products:
        orders = Order.query.filter_by(product_id=product.id).all()
        for order in orders:
            user_profile = Profile.query.filter_by(user_id=order.buyer_id).first()
            user_list.append(user_profile)
            order_list.append(order)
            product_list.append(product)
    stat_dict = {   
        "PENDING":"未付款",
        "PURCHASED":'买家已付款',
        "DELIVERED":'卖家已发货',
        "COMPLETED":'已完成',
        "CANCELLED":"已取消"
    }
    
    return render_template("seller_order.html",
                            products=product_list,
                            orders=order_list,
                            users=user_list,
                            length=len(order_list),
                            stat_dict=stat_dict)

    
        


@app_seller.route("/release", methods=["GET", "POST"])
def seller_release():
    if request.method == "GET":
        return render_template("seller_release.html")
    else:
        # 使用POST方法,发送FromData对象,
        # 获取商品文字信息,并存储
        name = request.form.get('name')
        description = request.form.get('description')
        price = int(request.form.get('price'))
        print(name, description, price)
        product = Product(seller_id =current_user.id,name=name,description=description,price=price)
        db.session.add(product)
        db.session.commit()

        # 获取商品图片并存储到saihan/static/images/products/...文件中
        upload_folder = current_app.config['UPLOAD_FOLDER']
        prod_img = request.files.get('picture')
        # 更改文件名,使用时间字符串防止重名
        ftime = datetime.datetime.now().strftime("%Y%m%d%H%M%S%f") 
        ext = prod_img.filename.split(".")[-1]  # 获取文件扩展名
        prod_filename = ftime+"."+ext 
        prod_img.save(os.path.join(upload_folder, "products/"+prod_filename))
        picture = ProductMedia(product_id = product.id,filename = prod_filename)
        db.session.add(picture)
        db.session.commit()

        return jsonify({"resultCode":200})
    

saihan/seller/templates/seller_items.html
{% extends "sellerlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<!-- <a href="index.html" class="logo fl"><img src="1234.jpg"></a> -->
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:100%"
		></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;商家中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>商家中心</h3>
			<ul>
				<li><a href="{{url_for('seller.seller_items')}}" class="active">· 管理商品</a></li>
				<li><a href="{{url_for('seller.seller_release')}}">· 发布商品</a></li>
				<li><a href="{{url_for('seller.seller_order')}}">· 管理订单</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">账户信息</h3>
						<ul class="user_info_list" style="height: auto;">
							<li><span>用户名：</span>{{ profile.nickname }}</li>
							<li><span>联系方式：</span>{{ profile.mobile }}</li>	
							<!-- <li><span>用户角色：</span>商家</li>	 -->
						</ul>
				</div>
				
				<h3 class="common_title2">商品操作</h3>
				
				<table id="cartTable">
						<thead>
						<tr>
						<!-- <th><label><input class="check-all check" type="checkbox"/> 全选</label></th> -->
						<th>商品</th>
						<th>单价</th>
						<th>状态</th>
						
						<th>操作</th>
						</tr>
						<tbody>
						{%for product in products %}
						<tr>
						<!-- <td class="checkbox"><input class="check-one check" type="checkbox" /></td> -->
						<td class="goods">
						<img src="{{ url_for('static', filename='images/products/'+product.attachments[0].filename) }}" alt="" />
						<span>{{ product.name }}</span></td>
						<td class="price">{{ product.price }}</td>
						<!-- <td class="count"><span class="reduce">-</span><input class="count-input" type="text" value="1"/><span class="add">+</span></td> -->
						<td class="subtotal">{{ prod_stat[product.status] }}</td>
						<td class="operation"><span class="delete">删除</span></td>
						</tr>
						{% endfor %}
						<!-- <tr>
						<td class="checkbox"><input class="check-one check" type="checkbox" /></td>
						<td class="goods"><img src="static/天天生鲜项目界面/images/2.jpg" alt="" /><span>Canon/佳能 PowerShot SX50 HS</span></td>
						<td class="price">3888.50</td> -->
						<!-- <td class="count"><span class="reduce">-</span><input class="count-input" type="text" value="1"/><span class="add">+</span></td> -->
						<!-- <td class="subtotal">3888.50</td>
						<td class="operation"><span class="delete">删除</span></td>
						</tr>
						<tr>
						<td class="checkbox"><input class="check-one check" type="checkbox" /></td>
						<td class="goods"><img src="static/天天生鲜项目界面/images/3.jpg" alt="" /><span>Sony/索尼 DSC-WX300</span></td>
						<td class="price">1428.50</td> -->
						<!-- <td class="count"><span class="reduce">-</span><input class="count-input" type="text" value="1"/><span class="add">+</span></td> -->
						<!-- <td class="subtotal">1428.50</td>
						<td class="operation"><span class="delete">删除</span></td>
						</tr>
						<tr>
						<td class="checkbox"><input class="check-one check" type="checkbox" /></td>
						<td class="goods"><img src="static/天天生鲜项目界面/images/4.jpg" alt="" /><span>Fujifilm/富士 instax mini 25</span></td>
						<td class="price">640.60</td> -->
						<!-- <td class="count"><span class="reduce">-</span><input class="count-input" type="text" value="1"/><span class="add">+</span></td> -->
						<!-- <td class="subtotal">640.60</td>
						<td class="operation"><span class="delete">删除</span></td> -->
						</tr>
						</tbody>
					   </table>
					   <div class="foot" id="foot">
						<!-- <label class=" fl select-all"><input type="checkbox" class="check-all check" /> 全选</label> -->
						<!-- <a class="fl delete" id="deleteAll" href="javascript:;" rel="external nofollow" >删除</a> -->
						<!-- <div class="fr closing">结 算</div> -->
						<!-- <div class="fr total">合计：￥<span id="priceTotal">0.00</span></div> -->
						<!-- <div class="fr select" id="selected">已选商品<span id="selectedTotal">0</span>件<span class="arrow up">︽</span><span class="arrow down">︾</span></div> -->
						<div class="selected-view">
						<div id="selectedViewList" class="clearfix">
						<div><img src="images/1.jpg"><span>取消选择</span></div>
						</div>
						<span class="arrow">◆<span>◆</span></span>
						</div>
					   </div>
				


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/seller/templates/seller_order.html
{% extends "sellerlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<!-- <a href="index.html" class="logo fl"><img src="1234.jpg"></a> -->
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:100%"
		></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;商家中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>商家中心</h3>
			<ul>
				<li><a href="{{url_for('seller.seller_items')}}">· 管理商品</a></li>
				<li><a href="{{url_for('seller.seller_release')}}">· 发布商品</a></li>
				<li><a href="{{url_for('seller.seller_order')}}" class="active">· 管理订单</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<!-- <h3 class="common_title2"></h3> -->
			<!-- 	<div class="site_con">
					<dl>
						<dt></dt>
						<dd></dd>
					</dl>					
				</div> -->
				<!-- <h3 class="common_title2"></h3> -->
				<!-- <div class="site_con"> -->
					<!-- <form> -->
				<div class="total_count">全部商品<em>{{length}}</em>件</div>	
				<ul class="cart_list_th clearfix">
					<li class="col01">商品名称</li>
					<li class="col02">买家姓名</li>
					<li class="col03">订单备注</li>
					<li class="col04">价格</li>
					<li class="col05">状态</li>
					<li class="col06">操作</li>
					
				</ul>
				{% for i in range(length) %}
				<ul class="cart_list_td clearfix">
					<li class="col01">
						<!-- <input type="checkbox" name="" checked> -->
						<!-- <select name="address">
							<option value="fa">发货</option>
							<option value="less">缺货</option>
						</select> -->
					</li>
				
					<li class="col02"><img src="{{url_for('static', filename='images/products/'+products[i].attachments[0].filename)}}"></li>
					<li class="col03"><p>{{products[i].name}}</p></li>
					<li class="col04"><p>{{users[i].nickname}}</p></li>
					<li class="col05"><p>{{orders[i].comments}}</p></li>
					<li class="col06"><p>{{products[i].price}}</p></li>

					<!-- <li class="col06">
						<div class="num_add">s
							<a href="javascript:;" class="add fl">+</a>
							<input type="text" class="num_show fl" value="1">	
							<a href="javascript:;" class="minus fl">-</a>	
						</div>s
					</li> -->
					<li class="col07"><p>{{stat_dict[orders[i].status]}}</p></li>
					<li class="col08"><a href="javascript:;">
						<!-- <input type="submit" value="确认"> -->
						<input type="submit" value="发货" name="ok">
						
					</a></li>
				</ul>
				{% endfor %}

					<!-- </form> -->
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/seller/templates/seller_release.html
{% extends "sellerlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<!-- <a href="index.html" class="logo fl"><img src="1234.jpg"></a> -->
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:100%"
		></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;商家中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>商家中心</h3>
			<ul>
				<li><a href="{{url_for('seller.seller_items')}}">· 管理商品</a></li>
				<li><a href="{{url_for('seller.seller_release')}}" class="active">· 发布商品</a></li>
				<li><a href="{{url_for('seller.seller_order')}}">· 管理订单</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">商品发布</h3>
				

				<!-- <div class="total_count">全部商品<em>1</em>件</div>	
				<ul class="cart_list_th clearfix">
					<li class="col01">商品名称</li>
					<li class="col02">商品单位</li>
					<li class="col03">商品价格</li>
					 <li class="col04">数量</li> -->
					<!-- <li class="col05">合计</li>
					<li class="col06">操作</li>
				</ul>
				<ul class="cart_list_td clearfix">
					<li class="col01"><input type="checkbox" name="" checked></li>
					<li class="col02"><img src="images/goods/goods012.jpg"></li>
					<li class="col03"><input type="text" placeholder="商品名称" style="width:70px;"></li>
					<li class="col04"><input type="text" placeholder="单位" style="width:70px;">
					<li class="col05"><input type="text" placeholder="商品价格" style="width:70px;"></li> --> 
					<!-- <li class="col06">
						<div class="num_add">
							<a href="javascript:;" class="add fl">+</a>
							<input type="text" class="num_show fl" value="1">	
							<a href="javascript:;" class="minus fl">-</a>	
						</div>
					</li> -->
					<!-- <li class="col07"><input type="text" placeholder="合计金额" style="width:70px;"></li>
					<li class="col08"><a href="javascript:;">
						<input type="submit" value="发布">
					</a></li>
				</ul> -->
				<div class="reg_form clearfix">
					<form class="prod_release">
					<ul>
						<li>
							<label>商品名称:</label>
							<input type="text" name="name">
						</li>					
						<li>
							<label>详细信息:</label>
							<input type="text" name="description">
						</li>
						<li>
							<label>金额:</label>
							<input type="number" name="price">
						</li>
						<li>
							<label>图片:</label>
							<input type="file" name="picture" style="border: none;background-color: white;margin-top: 8px;">
							<!-- <input type="text" name="email" id="email">
							<span class="error_tip">提示信息</span> -->
						</li>
						<li class="reg_sub">
							<input type="button" onclick="release()" value="提 交" style="text-align:center;">
						</li>
					</ul>				
					</form>
				</div>
				
		</div>
	</div>
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript">
        function release() {
            var form = $(".prod_release")[0];
            console.log(form)
            var fd = new FormData(form);
            console.log(fd.get("price"));
            $.ajax({
            //几个参数需要注意一下
                type: "POST",//方法类型
                url: "{{ url_for('seller.seller_release') }}" ,//url
                data: fd,
                processData: false,  // 不处理数据
			  	contentType: false,  // 不设置内容类型
                success: function (result) {
                    console.log(result);//打印服务端返回的数据(调试用)
                    if (result.resultCode == 200) {
                        alert("提交成功");
                    }
                    ;
                },
                error : function() {
                    alert("提交失败！");
                }
            });
        }
    </script>
	
</body>
{% endblock %}

saihan/seller/templates/sellerlayout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>赛汉-专注二手商品</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/seller.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/reset.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-1.12.4.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-ui.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/slide.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/cart.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/register.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/seller_items.js')}}"></script>
    <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon">
</head>
<body>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到赛汉!</div>
            <div class="fr">
                {% if current_user.is_authenticated%}
                    <div class="login_info fl" style="display:block;">
                        欢迎您：<em>{{current_user.username}}</em>
                    </div>
                    <div class="login_btn fl">
                        <span>|</span>
                        <a href="{{url_for('common.logout')}}">登出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{{url_for('common.login')}}">登录</a>
                        <span>|</span>
                        <a href="{{url_for('common.register')}}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{{url_for('seller.seller_items')}}">商家中心</a>
                    <span>|</span>
                    <a href="{{url_for('seller.seller_release')}}">发布商品</a>
                </div>
            </div>
        </div>      
    </div>
{% block body %}
{% endblock %}
</body>
</html>