saihan/adver/__init__.py
# coding:utf-8

from flask import Blueprint


# 创建蓝图对象
app_adver = Blueprint("adver", __name__, template_folder="./templates")


# 导入蓝图的视图
from . import views

saihan/adver/views.py
# coding:utf-8

from . import app_adver
from saihan import db
from flask import render_template
import saihan.models as models
# from saihan.models import ..

# 广告界面
@app_adver.route("/manage")
def adver_manage():
    user1 = {
    'img_url':'guanggao1.jpg',
    'xinxi':'神犬小七',
    'jine':'3000'
    }
    user2 ={
    'img_url':'guanggao3.jpg',
    'xinxi':'招聘信息',
    'jine':'5000'
    }
    users = [user1, user2]
    return render_template("adver_manage.html",users=users,name='张三')

@app_adver.route("/release")
def adver_release():
    dic = {
    'name':'李四'
    }
    return render_template("adver_release.html",d1=dic)

saihan/adver/templates/adver_cart.html
<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title>Document</title>
  <link rel="stylesheet" href="static/css/cart.css" type="text/css">
  <script src="static/js/jquery-1.11.3.js"></script>
  <script src="static/js/cart.js"></script>
 </head>
 <body>
	<div id="container">
		<!-- 1. 导航 -->
		<div id="nav">
			<!-- 1.1 右侧导航 -->
			<ul class="rightNav">
				<li>
					<a href="">[ 登录 ]</a>
					<a href="">[ 注册有惊喜 ]</a>
				</li>
				<li>
					<a href="">赛汉公告</a>
				</li>
				<li>
					<a href="">券卡兑换</a>
				</li>
				<li class="lastItem">
					<a href="">返回首页</a>
				</li>
			</ul>
			<!-- 1.2 左侧导航 -->
			<ol class="leftNav">
				<li>
					<span>上海</span>
					<i></i>
				</li>
				<li>满百包邮(环郊内)</li>
				<li>
					<a href="">星夜达</a>
				</li>
			</ol>
			
		</div>
		<!-- 2. 横幅banner -->
		<!-- <div id="banner">
			<img src="static/images/images1/banner1.jpg">
		</div> -->
		<!-- 3. 推荐 -->
		<!-- <div id="commend">
			<a href="">
				<img src="static/images/images1/{{photo}}">
			</a>

			<a href="">
				<img src="static/images/images1/{{photo}}">
			</a>
			<a href="">
				<img src="static/images/images1/{{photo}}">
			</a>
			<a href="">
				<img src="static/images/images1/{{photo}}" class="lastImg">
			</a>
		</div> -->
		<!-- 4. 主体 -->
		<div id="main">
			<!-- 上方标题栏(工具栏)-->
			<div class="title">
				<p class="check-box">
					<input type="checkbox" name="checkAll" id="checkAll">
					全选
				</p>
				<p class="goods">商品</p>
				<p class="price">单价</p>
				<p class="count">数量</p>
				<p class="sum">小计<p>
				<p class="action">操作</p>
			</div>

			<!-- 下方商品记录-->
			<div class="content">
				{%for i in cart%}
				<div class="g-item">
					<p class="check-box">
						<input type="checkbox" name="check">
						<img src="static/images/images1/{{i['attachments']}}">
					</p>
					<p class="goods">啊啊啊</p>
					<p class="price">&yen;{{i['price']}}</p>
					<p class="count">
						<a href="javascript:void(0)" class="minus">-</a>
						<input type="text" value="1">
						<a href="javascript:void(0)" class="add">+</a>
					</p>
					<p class="sum">
						<b>&yen;188</b>
					</p>
					<p class="action">移除</p>
				</div>
				{%endfor%}
				
			{#	<div class="g-item">
					<p class="check-box">
						<input type="checkbox" name="check">
						<img src="static/images/images1/1-270x270-2109-SDK5WUW8.jpg">
					</p>
					<p class="goods">欢乐时光水果果篮</p>
					<p class="price">&yen;188</p>
					<p class="count">
						<a href="javascript:void(0)" class="minus">-</a>
						<input type="text" value="1">
						<a href="javascript:void(0)" class="add">+</a>
					</p>
					<p class="sum">
						<b>&yen;188</b>
					</p>
					<p class="action">移除</p>
				</div>
				<div class="g-item">
					<p class="check-box">
						<input type="checkbox" name="check">
						<img src="static/images/images1/1-270x270-2109-SDK5WUW8.jpg">
					</p>
					<p class="goods">欢乐时光水果果篮</p>
					<p class="price">&yen;188</p>
					<p class="count">
						<a href="javascript:void(0)" class="minus">-</a>
						<input type="text" value="1">
						<a href="javascript:void(0)" class="add">+</a>
					</p>
					<p class="sum">
						<b>&yen;188</b>
					</p>
					<p class="action">移除</p>
				</div>
				<div class="g-item">
					<p class="check-box">
						<input type="checkbox" name="check">
						<img src="static/images/images1/1-270x270-2109-SDK5WUW8.jpg">
					</p>
					<p class="goods">欢乐时光水果果篮</p>
					<p class="price">&yen;188</p>
					<p class="count">
						<a href="javascript:void(0)" class="minus">-</a>
						<input type="text" value="1">
						<a href="javascript:void(0)" class="add">+</a>
					</p>
					<p class="sum">
						<b>&yen;188</b>
					</p>
					<p class="action">移除</p>
				</div>
				#}
			</div>
		
		</div>
		<!-- 5. 底部 -->
		<div id="cart-toolbar">
			<div class="right-toolbar">
				<p class="submit-count">
					已选择<span></span>件商品
				</p>
				<p class="submit-price">
					共计 : <span></span>
				</p>
				<p class="submit-btn">去结算</p>
			</div>
		
		</div>
	
	</div>
 </body>
</html>

saihan/adver/templates/adver_manage.html
{% extends "adverlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="{{ url_for('common.index') }}" class="logo fl"><img src="{{url_for('static', filename='images/logo/saihan.png')}}" style="width:100%;height:100%"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;广告商中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索广告类型">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>广告中心</h3>
			<ul>
				<li><a href="{{url_for('adver.adver_manage')}}" class="active">· 管理已有广告</a></li>
                <li><a href="{{url_for('adver.adver_release')}}">· 发布新广告</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<!-- <div class="info_con clearfix">
				</div> -->
				
				<h3 class="common_title2">已有广告</h3>
				<div class="has_view_list">
					<ul class="cart_list_th clearfix">
						<li class="col01">广告图片样式</li>
						<li class="col02">详细信息</li>
						<li class="col03">编辑</li>
						<li class="col05">金额(元)</li>
						<li class="col06">删除</li>
					</ul>

					{%for user in users%}
					<ul class="cart_list_td clearfix">
						<li class="col01"><input type="checkbox" name="" checked></li>
						<li class="col02"><img src="static/images/guanggao/{{ user['img_url'] }}"></li>
						<li class="col03"> <br></li>
						<li class="col04">{{user['xinxi']}}</li>
						<li class="col05"><a href="">点击编辑信息</a></li>
						<li class="col07">{{ user['jine']}}</li>
						<li class="col08"><a href="javascript:;">删除</a></li>
					</ul>
					{% endfor %}



				
{#					<ul class="cart_list_td clearfix">
						<li class="col01"><input type="checkbox" name="" checked></li>
						<li class="col02"><img src="static/images/guanggao/{{ user['img_url1'] }}"></li>
						<li class="col03"> <br></li>
						<li class="col04">{{user['xinxi1']}}</li>
						<li class="col05"><a href="">点击编辑信息</a></li>
						<li class="col07">{{user['jine1']}}</li>
						<li class="col08"><a href="javascript:;">删除</a></li>
					</ul>
					#}



					
		</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 天津赛汉科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/adver/templates/adver_release.html
{% extends "adverlayout.html" %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="{{ url_for('common.index') }}" class="logo fl"><img src="{{url_for('static', filename='images/logo/saihan.png')}}" style="width:100%;height:100%"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;广告商中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索广告类型">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>广告中心</h3>
			<ul>
				<li><a href="{{url_for('adver.adver_manage')}}">· 管理已有广告</a></li>
                <li><a href="{{url_for('adver.adver_release')}}" class="active">· 发布新广告</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">			
				<h3 class="common_title2">广告发布</h3>
				<!-- <div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="images/goods/goods003.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods004.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods005.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods006.jpg"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="images/goods/goods007.jpg"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div> -->
			<div class="has_view_list">
				<div class="reg_form clearfix">
					<form>
					<ul>
						<li>
							<label>广告名:</label>
							<input type="text" name="user_name" id="user_name" placeholder="">
							<span class="error_tip">提示信息</span>
						</li>					
						<li>
							<label>详细信息:</label>
							<input type="text" name="pwd" id="pwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>金额:</label>
							<input type="text" name="cpwd" id="cpwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>图片:</label>
							<input type="file" name="tutu" style="border: none;background-color: white;margin-top: 8px;">
							<!-- <input type="text" name="email" id="email">
							<span class="error_tip">提示信息</span> -->
						</li>
						<li class="reg_sub">
							<a href="">
								<input type="submit" value="提 交" name="">
							</a>
						</li>
					</ul>				
					</form>
				</div>
				<!-- <div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">....</a>
					<a href="#">下一页></a>
				</div> -->
			</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 天津赛汉科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
{% endblock %}

saihan/adver/templates/adverlayout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>赛汉-广告商中心</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/adver.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/reset.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-1.12.4.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery-ui.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/slide.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/cart.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/register.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/seller_items.js')}}"></script>
    <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon">
</head>
<body>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到赛汉广告商主题!</div>
            <div class="fr">
                {% if current_user.is_authenticated%}
                    <div class="login_info fl" style="display:block;">
                        欢迎您：<em>{{user.username}}</em>
                    </div>
                    <div class="login_btn fl">
                        <span>|</span>
                        <a href="{{url_for('common.logout')}}">登出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{{url_for('common.login')}}">登录</a>
                        <span>|</span>
                        <a href="{{url_for('common.register')}}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{{url_for('adver.adver_manage')}}">广告商中心</a>
                    <span>|</span>
                    <a href="{{url_for('adver.adver_release')}}">发布新广告</a>
                </div>
            </div>
        </div>      
    </div>
{% block body %}
{% endblock %}