saihan/common/__init__.py
# coding:utf-8

from flask import Blueprint


# 创建蓝图对象
app_common = Blueprint("common", __name__, template_folder="./templates")


# 导入蓝图的视图
from . import views
from . import insert

saihan/common/views.py
# coding:utf-8

from . import app_common
from saihan import db, login_manager
from flask import render_template, request, session, redirect, url_for, jsonify
from saihan.models import User, Profile, Product
from flask_login import login_user, current_user, login_required, logout_user
from saihan.libs.yuntongxun.sms import CCP
sms_code = 0 
import random


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()

@login_manager.unauthorized_handler
def unauthorized():
    return render_template("error.html", error="未登录")

@app_common.route("/index")
def index():
    products = Product.query.all()
    user_type = { 
        "PERSONAL": "个人",
        "BUSINESS":  "商家",
        "ADVERTISEMENT": "广告商",
        "ADMINISTRATOR": "管理员"
    }
    return render_template("index.html", 
                           user=current_user,
                           user_type=user_type,
                           products=products)

@app_common.route("/register", methods=["POST", "GET"])
def register():
    """注册
    请求的参数： 手机号、短信验证码、密码、确认密码
    参数格式：表单数据
    """
    method = request.method
    # 如果是get方法,返回静态页面
    if request.method == "GET":
        return render_template("register.html")

    # 如果是POST方法,则获取请求的表单数据，返回字典
    req_dict = request.form.to_dict()
    # print(dir(req_dict))

    username = req_dict.get("username")
    password = req_dict.get("pwd")
    password2 = req_dict.get("cpwd")
    mobile = req_dict.get("mobile")
    newsms_code = req_dict.get("newsms_code")
    if sms_code != newsms_code:
        return render_template("error.html", error="验证码错误")
    # print(username)
    # print(password)

    # 校验参数
    if not all([username, password, password2, mobile, newsms_code]):
        return render_template("error.html", error="参数不完整")

    # 密码验证
    if password != password2:
        return render_template("error.html", error="两次密码不一致")

    # 判断用户是否注册过
    try:
        user = User.query.filter_by(username=username).first()
    except Exception as e:
        raise
        return render_template("error.html", error="数据库异常")
    else:
        if user is not None:
            # 表示用户已存在
            return render_template("error.html", error="用户已存在")

    # 保存用户的注册数据到数据库中
    user = User(username=username, type="PERSONAL")
    user.password = password  # 设置属性
    print(user.password_hash)
    try:
        db.session.add(user)
        db.session.commit()
    except IntegrityError as e:
        # 数据库操作错误后的回滚
        db.session.rollback()
        raise
        return render_template("error.html", error="用户已存在")
    except Exception as e:
        db.session.rollback()
        raise
        return render_template("error.html", error="查询数据库异常")
    # # 返回结果
    # return jsonify(errno=RET.OK, errmsg="注册成功")
    # 注册成功自动生成个人资料
    profile = Profile(user_id=user.id, mobile=mobile, nickname=username, avatar="saihan.png")
    db.session.add(profile)
    db.session.commit()

    return render_template("error.html", error="注册成功")



@app_common.route("/login", methods=["GET", "POST"])
def login():
    """用户登录
    参数： 用户名、密码
    """
    # 检查请求方式，GET请求返回登录页面
    method = request.method
    if method == "GET":
        return render_template("login.html")
    # 获取参数
    req_dict = request.form.to_dict()
    # print(req_dict)
    username = req_dict.get("username")
    password = req_dict.get("pwd")

    # 校验参数
    # 参数完整的校验
    if not all([username, password]):
        return render_template("error.html", error="参数不完整")

    # 从数据库中根据手机号查询用户的数据对象
    try:
        user = User.query.filter_by(username=username).first()
    except Exception as e:
        raise
        return render_template("error.html", error="获取用户信息失败")

    # 用数据库的密码与用户填写的密码进行对比验证
    if user is None or not user.check_password(password):
        return render_template("error.html", error="用户名或密码错误")

    login_user(user)
    # print(user)
    # 如果验证相同成功，保存登录状态， 在session中
    # return render_template("error.html", error=user.type)
    if user.type == "PERSONAL":
        return redirect(url_for("common.index"))
    elif user.type == "BUSINESS":
        return redirect(url_for("seller.seller_items"))
    elif user.type == "ADVERTISEMENT":
        return redirect(url_for("adver.adver_manage"))
    elif user.type == "ADMINISTRATOR":
        return redirect(url_for("admin.admin_user"))

@app_common.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("common.index"))

@app_common.route("/smscode")
@app_common.route("/smscode/<mobile>", methods=["GET", "POST"])
def smscode(mobile=None):
     # 生成短信验证码
    global sms_code
    sms_code = "%06d" % random.randint(0, 999999)

    #定义mobile的手机号
    try:
        ccp = CCP()
        result = ccp.send_template_sms(mobile, [sms_code, 5], 1)
    except Exception as e:
        print(e)
        return ""
    # 返回值
    # 发送成功
    r = {"mobile":mobile}
    return jsonify(r)

saihan/common/templates/error.html
{% extends "layout.html"%}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="{{url_for('static', filename='images/logo/saihan.png')}}"></a>
        </div>

        <div class="r_con fr" style="padding:10% 0;">
            <div class="reg_title clearfix">
                <h1>{{ error }}</h1>
                <a href="" onclick="history.back()">返回</a>
            </div>
        </div>

    </div>

{% endblock %}

saihan/common/templates/index.html
{% extends 'layout.html' %}
{% block body %}

	<div class="search_bar clearfix">
		<a href="{{url_for('common.index')}}" class="logo fl"><img src="{{ url_for('static', filename='images/logo/saihan.png') }}" style="width: 100%; height:100%"
		></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
	
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<!-- <li class="interval">|</li> -->
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">书籍</a></li>
			<li><a href="#model02" class="seafood">二手房</a></li>
			<li><a href="#model03" class="meet">手表</a></li>
			<li><a href="#model04" class="egg">汽车</a></li>
			<li><a href="#model05" class="vegetables">电脑</a></li>
			<li><a href="#model06" class="ice">手机</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{{url_for('static', filename='images/banner/001.jpg')}}" alt="幻灯片"></li>
				<li><img src="{{url_for('static', filename='images/banner/002.jpg')}}" alt="幻灯片"></li>
				<li><img src="{{url_for('static', filename='images/banner/003.jpg')}}" alt="幻灯片"></li>
				<li><img src="{{url_for('static', filename='images/banner/004.jpg')}}" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		        <div class="adv fl" style="box-sizing:border-box; background-color: white; text-align: center;    border-bottom: 1px solid #eee; border-right: 1px solid #eee;">
				{% if current_user.is_authenticated %}
					<a href="#" style="width: 100%; height: 55%;padding:20px 0 10px;"><img src='{{ url_for("static", filename="images/usericon/"+user.profile[0].avatar) }}' style="width:135px;height:135px;border-radius: 50%;margin:0 auto;"></a>
					<div class="login_info fl" style="display:block;box-sizing:border-box;width:100%;height:15%;line-height:40px;text-align: center;">
		            欢迎来到赛汉：<em>{{ user.profile[0].nickname }}</em>
		            </div>
		            <div class="login_info fl" style="display:block;box-sizing:border-box;width:100%;height:15%;text-align: center;">
		            用户类型：<em>{{ user_type[user.type] }}</em>
		        	</div>
            	{% else %}
                	<a href="{{url_for('common.login')}}" style="width: 100%; height: 55%;padding:20px 0 10px;font-size:24px;line-height: 178px;">请登录</a>
            	{% endif %}
                </div>
		
	</div>

	<!-- 商品列表 -->
	<div class="list_model" style="height:auto; background: #f5f5f5;">
		<div class="list_title clearfix" style="height:0;margin-bottom: 20px;">

		</div>

		<div class="item-list">
			<div class="item-list-wrap">
				<!-- 循环获取商品 -->
				{% for product in products %}
				{% if product.status == "SELLING" %}
				<a href="{{ url_for('user.detail', product_id=product.id) }}" class="item-wrap">
					<div class="item-img" style="background-image: url({{ url_for('static', filename='images/products/'+product.attachments[0].filename) }})"></div>
					<div class="item-info">
						<p class="item-title">{{product.name}}</p>
						<p class=""></p>
						<div class="price-line">
							<p class="price-unit">￥</p>
							<p class="price-value">{{product.price}}</p>
						</div>
					</div>
					<div class="user-line">
						<div class="user-info">
							<img src="{{url_for('static', filename='images/usericon/'+product.seller.avatar)}}" class="usericon">
							<p class="user-name">{{product.seller.nickname}}</p>
							<img src="{{url_for('static', filename='images/usertag/level0.png')}}" class='user-tag'>
						</div>
					</div>
				</a>
				{% endif %}
				{% endfor %}

			</div>
		</div>
	</div>
{% endblock %}

saihan/common/templates/layout.html
{% from 'macros.html' import import_css, import_js, top_nav, footer %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {{  import_css(['common.css', 'reset.css', 'plist.css']) }}
    {{  import_js(['jquery-1.12.4.min.js', 'jquery-ui.min.js', 'slide.js', 'cart.js', 'register.js']) }}
    <title>赛汉-专注二手商品</title>
</head>
<body>
{{ top_nav(current_user) }}

{% block body %}
{% endblock %}

{{ footer() }}
</body>
</html>

saihan/common/templates/login.html
{% extends "layout.html"%}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{{url_for('static', filename='images/logo/saihan.png')}}"></a>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户登录</h1>
				<a href="register">注册</a>
			</div>
			<div class="reg_form clearfix">
				<form method="POST" action="login">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<!-- <li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”赛汉用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li> -->
					<li class="reg_sub">
						<input id="submit-button" type="submit" value="登 录" name="">
					</li>
				</ul>				
				</form>
			</div>
		</div>
	</div>
{% endblock %}

saihan/common/templates/macros.html
<!-- 引入css -->
{% macro import_css(files) %}
    {% for file in files %}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/'+file)}}">
    {% endfor %}
    <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon">
{% endmacro %}

<!-- 引入javascript -->
{% macro import_js(files) %}
    {% for file in files %}
    <script type="text/javascript" src="{{url_for('static', filename='js/'+file)}}"></script>
    {% endfor %}
{% endmacro %}

<!-- 头部导航栏 -->
{% macro top_nav(current_user) %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到赛汉!</div>
            <div class="fr">
                {% if current_user.is_authenticated %}
                    <div class="login_info fl" style="display:block;">
                        欢迎您：<em>{{current_user.username}}</em>
                    </div>
                    <div class="login_btn fl">
                        <span>|</span>
                        <a href="{{url_for('common.logout')}}">登出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{{url_for('common.login')}}">登录</a>
                        <span>|</span>
                        <a href="{{url_for('common.register')}}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    {% if current_user.type == "PERSONAL" %}
                    <span>|</span>
                    <a href="{{url_for('user.user_info')}}">用户中心</a>
                    <span>|</span>
                    <a href="{{url_for('user.user_order')}}">我的订单</a>
                    {% endif %}
                </div>
            </div>
        </div>      
    </div>
{% endmacro %}

<!-- 页面底部 -->
{% macro footer() %}
    <div class="footer no-mp">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>        
        </div>
        <p>CopyRight © 2016 All Rights Reserved</p>
        <p>电话：010-****888    京ICP备*******8号</p>
    </div>
{% endmacro %}

saihan/common/templates/pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>确认支付</title>
    <style>
        body{
            text-align: center;
        }
    </style>
</head>
<body>

    <img src="{{ url_for('static', filename='images/payicons/pay.jpg') }}"></img>
    <p>
        <a href="{{ url_for('common.index') }}" type="submit">支付完成，回到首页</a>
    </p>
    
</body>
</html>

saihan/common/templates/register.html
{% extends "layout.html" %}
{% block body %}

	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{{url_for('static', filename='images/logo/saihan.png')}}"></a>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="login">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="POST" action="register">
				<ul>
					<li>
						<label>用户名:</label> 
						<input type="text" name="username" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>手机号:</label>
						<input type="text" name="mobile" id="mobile" >
						<div class="phonecode">
						</div>
						<span class="error_tip">提示信息</span>
						<!-- <input id="submit-button" type="submit" value="获取验证码" name=""> -->
						<!-- <button class="button"  -->
						
					</li>
					<li>
						<!-- 昨天改的 -->
						<label>验证码:</label>
						<input style="display: inline-block;width:160px;" type="text" class="form-control" name="newsms_code" id="mobile" required>
						<input style="display: inline-block;width:auto;height:40px;padding:0 10px;border-left:none;" type="button" name="b1" onclick="fsubmit()" value="获取短信验证码 " />
					</li>
					<!-- <li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”赛汉用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li> -->
					<li class="reg_sub">
						<input id="submit-button" type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>
	</div>
	<script type="text/javascript">
        function fsubmit() {
            var mobile = $("input[name='mobile']").val();
            console.log(mobile);
            var button = $("input[name='b1']");
            button.disabled = "disabled";
            button.value="等待60s再次发送";
            fetch("{{ url_for('common.smscode') }}"+"/"+mobile)
            .then(function(response) {
                return response.json();
            })
            .then(function(myJson) {
                console.log(myJson);
            });

        }
        </script>

{% endblock %}